apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: leonardohildt/mifos-app
  newName: leonardohildt/mifos-app
  newTag: af906e5
- name: leonardohildt/mifos-app:leonardohildt/mifos-app
  newTag: 3511c83
