name: CI Latam Mifos
on:
  push:
    branches:
      - fiter/latam/dev
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: leonardohildt/mifos-app
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME}}
jobs:
  build-and-push-image:
    name: CI Latam Mifos
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: write
      discussions: read
      packages: read
      pages: read
      pull-requests: write
      repository-projects: write
      security-events: read
      statuses: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Info
        run: echo "Parameters. ${{ github.event.base_ref }}, ${{ github.ref_type }}, ${{ github.ref }}"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Checkout remote repo
        uses: actions/checkout@v3
        with:
          repository: leomax060778/argocd-poc
          token: ${{ secrets.PTA }}
          path: argocd-poc

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        run: |
          cd /home/runner/work/community-app/community-app/argocd-poc
          cd poc4/manifests
          kustomize edit set image ${{ steps.metadata.outputs.tags }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          cd /home/runner/work/community-app/community-app/argocd-poc
          cd poc4
          git config --global credential.helper store
          git config --local user.email leonardohildt@gmail.com
          git config --local user.name leomax060778
          git add manifests
          git commit -am "Bump docker tag to ${{ steps.metadata.outputs.tags }}"
          git push